[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "sh -c 'cd epharm && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn epharm.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --threads 2 --timeout 60'"
healthcheckPath = "/api/products/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
